INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcosrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'john.vliweeqwssides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Maradsdsacos', 'Ruiz', 'mardsadsacosrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'johdasdsan.doe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linudasdass.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.ledsadsardorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamdsadsama@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richard.hedsadsalm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johdasdsanson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'johdsadsan.vlissides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'jamedsadass.gosling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.ledsaadse@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornsaddsaado.roe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'janeadsdas.doe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcohjhgghjsrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'joh5445n.doe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'lin64545us.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasm64465us.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.ga6464mma@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richard.h465465elm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.jorterhnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gos0ling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.le0e@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe1@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.do1e@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcosr0m99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'john.do2e@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linu3s.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmu4s.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.ga5mma@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richa6rd.helm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.j7ohnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'john.vlis8sides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gos5ling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.5lee@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornado.r5oe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.d4oe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcosrm9559@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'john.d4oe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torv4alds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdforf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamama@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richard.heslm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnsonf@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'joahn.vlissides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'jamdes.gosling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmafil.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornado.vroe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.dobe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'maercasdosrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'john.dwoe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linaus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmuads.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gasdmma@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richaadsrd.helm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralpdsah.johnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'john.vladsissides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'jaiumes.gosling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.leoiue@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornuoiado.roe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jauoine.doe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcouiosrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'johqewn.doe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'li12nus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmrus.lerrwedorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gammwera@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richard.hwreelm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.jwreohnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'john.vliwressides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gowresling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.wrelee@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornawerdo.roe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.dweroe@gmail.com', '2018-03-06');

INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Marcos', 'Ruiz', 'marcoswerwerrm99@bolsadeideas.com', '2018-01-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Mr. John', 'Doe', 'john.dwerroe@gmail.com', '2018-01-02');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Linus', 'Torvalds', 'linurews.torvalds@gmail.com', '2018-01-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmrewus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamwrema@gmail.com', '2018-02-01');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Richard', 'Helm', 'richaqewrd.helm@gmail.com', '2018-02-10');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Ralph', 'Johnson', 'ralppioh.johnson@gmail.com', '2018-02-18');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('John', 'Vlissides', 'johnp.vlissides@gmail.com', '2018-02-28');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Dr. James', 'Gosling', 'ja321mes.gosling@gmail.com', '2018-03-03');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Magma', 'Lee', 'magma.le32e@gmail.com', '2018-03-04');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Tornado', 'Roe', 'tornad23o.roe@gmail.com', '2018-03-05');
INSERT INTO clients (first_name, last_name, email, create_at) VALUES('Jade', 'Doe', 'jane.d111oe@gmail.com', '2018-03-06');